title: Home
preset: page


sections:  
  siteContent:
    type: fields
    fields:
      title:
        label: Page Title
        type: text
      subtitle:
        label: Page Subtitle
        type: text
      intro:
        label: Page Intro
        type: text

      sections_header:
        label: Sections
        type: headline
        numbered: true

      sections:
        label: ' '
        type: structure
        fields:
          section_header:
            label: Section Header
            type: text
          id_name:
            label: '#css-id'
            type: text
          section_body:
            label: Section Body
            type: textarea
          section_image:
            label: Section Image
            type: files

      comments_header:
        label: Comments Header
        type: headline
      enable_comments:
        label: Enable Comments
        type: toggle

      comments:
        label: Comments
        type: structure
        fields:
          commentName:
            label: Name
            type: text
          commentEmail:
            label: Email
            type: email
          commentcontent:
            label: Content
            type: textarea
          commentDate:
            label: Date
            type: date
            time: true
          commentPublished:
            label: Published
            type: toggle
            default: false

      footer_header:
        label: Footer
        type: headline
        numbered: true

      footer:
        label: Footer Text
        type: textarea

      line:
        type: line

  stats:
    type: stats
    reports:
      - label: Pending Comments
        value: "{{ site.numberOfPendingComments }}"
        info: "Possible spam: {{ site.numberOfSpamComments }}"
        theme: negative
