title: Home
preset: page

fields:
  title:
    label: Page Title
    type: text
  subtitle:
    label: Page Subtitle
    type: text
  intro:
    label: Page intro
    type: text
  
  sections:
    label: Sections
    type: structure
    fields:
      section_header:
        label: Section Header
        type: text
      id_name:
        label: '#css-id'
        type: text
      section_body:
        label: Section Body
        type: textarea
      section_image:
        label: Section Image
        type: files
  
  footer:
    label: Footer Text
    type: textarea
